version: "3.8"

services:
  # orchestrator:
  #   build: ./orchestrator
  #   ports:
  #     - "8001:8000"
  #   env_file:
  #     - ./orchestrator/.env
  #   volumes:
  #     - ./orchestrator:/app
  #   networks:
  #     - app-network
  
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service:/app
    networks:
      - app-network
  
  credential-broker-service:
    build: 
      context: ./credential-broker-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - ./credential-broker-service/.env
    volumes:
      - ./credential-broker-service:/app
    networks:
      - app-network
  

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: