version: "3.8"

services:
  # orchestrator:
  #   build: ./orchestrator
  #   ports:
  #     - "8001:8000"
  #   env_file:
  #     - ./orchestrator/.env
  #   volumes:
  #     - ./orchestrator:/app
  #   networks:
  #     - app-network
  
  # github-mcp:
  #   build: ./mock-mcps/github-mcp
  #   ports:
  #     - "8101:8080"
  #   networks:
  #     - app-network

  # qa-generator-mcp:
  #   build: ./mock-mcps/qa-generator-mcp
  #   ports:
  #     - "8102:8080"
  #   networks:
  #     - app-network

  # postgres-writer-mcp:
  #   build: ./mock-mcps/postgres-writer-mcp
  #   ports:
  #     - "8103:8080"
  #   networks:
  #     - app-network
  
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:80"
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service:/app
    networks:
      - app-network
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: