"""Community summarizer (STORY-4b).

Generates summaries for community kinds that aren't covered by the
entity-Leiden Celery path. Today: chunk-Louvain communities only.

Designed for three callers:

1. The ``POST /graphs/{id}/communities/summarize`` endpoint.
2. Future agent tools — ``describe_community`` can call
   ``summarize_one`` on demand if a community has no stored summary
   (STORY-4d). The class is intentionally callable from anywhere.
3. A future Celery task wrapper if auto-summarisation-on-detect is wired
   when chunk-community detection itself gets a Celery task.

Why not entity-Leiden too
-------------------------
Entity-level summaries are already generated by the Celery detector
(``community_tasks.detect_communities_task`` → ``analytics_service._generate_level_summaries``)
and have a stable test surface. Folding both kinds into one class is a
worthwhile refactor but out of scope for STORY-4b; for now this
summarizer only handles flat read-only kinds (currently just ``chunk``).
Adding another flat kind in the future: extend the registry, then add
one branch in ``summarize_all``.

Write shape (chunk communities)
-------------------------------
- ``cc.summary`` — 2-3 sentence prose. Self-contained; embedded for
  vector search in STORY-4c.
- ``cc.summary_keywords`` — JSON-encoded list of 5-10 key entities or
  topics. Used by the future ``describe_community`` agent tool to
  return structured data without parsing the prose.
- ``cc.summary_excerpt`` — up to 500 chars from the single most
  representative member chunk. Lets ``describe_community`` return
  concrete evidence.
- ``cc.summary_model`` / ``cc.summary_at`` / ``cc.summary_sampled`` /
  ``cc.summary_member_count`` — provenance.
"""

from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass, field
from typing import Any

from openai import AsyncOpenAI

from app.core.config import settings
from app.core.logging import get_logger
from app.core.neo4j_client import neo4j_client
from app.schemas.community_kinds import (
    COMMUNITY_KINDS,
    UnknownCommunityKindError,
    get_kind,
)

logger = get_logger(__name__)


# Sampling for chunk-community summaries. K chunks per community,
# truncated to TRUNC chars each. Worst case for an Eurail-sized 6-cluster
# graph: 6 × 10 × 1500 = 90K chars ≈ ~22K input tokens — well within budget.
_CHUNK_SAMPLE_K = 10
_CHUNK_TRUNC_CHARS = 1500


# Strict JSON-output prompt for chunk-community summaries. Keeps the
# downstream extraction path simple and gives the LLM clear structural
# expectations. Falls back to a free-text summary if JSON parsing fails.
_CHUNK_PROMPT_TEMPLATE = (
    "Analyse this cluster of {sampled} chunks (out of {total} total). "
    "They were grouped together by a clustering algorithm because their "
    "content is closely related.\n\n"
    "Return ONLY a JSON object with three fields, no prose outside the JSON:\n"
    "{{\n"
    '  "summary": "2-3 sentences describing the dominant theme of this '
    'cluster. Self-contained — should make sense without reading the chunks.",\n'
    '  "keywords": ["list of 5-10 key entities, concepts, or topics that '
    'recurred across these chunks"],\n'
    '  "representative_excerpt": "Up to 500 chars from the single most '
    "representative chunk, quoted verbatim. Choose the chunk that best "
    "captures the cluster's theme.\"\n"
    "}}\n\n"
    "Chunks:\n{chunk_block}"
)


@dataclass(slots=True)
class SummarizeReport:
    """What happened when summarize_all ran for one graph + kind."""

    kind: str
    total: int = 0
    summarized: int = 0
    skipped_existing: int = 0
    skipped_singleton: int = 0
    failed: int = 0
    per_level: dict[str, int] = field(default_factory=dict)
    # STORY-4c — when the endpoint embeds summaries in the same call:
    embedded: int = 0
    skipped_existing_embeddings: int = 0
    failed_embeddings: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "total": self.total,
            "summarized": self.summarized,
            "skipped_existing": self.skipped_existing,
            "skipped_singleton": self.skipped_singleton,
            "failed": self.failed,
            "per_level": self.per_level,
            "embedded": self.embedded,
            "skipped_existing_embeddings": self.skipped_existing_embeddings,
            "failed_embeddings": self.failed_embeddings,
        }


@dataclass(slots=True)
class EmbedReport:
    """What happened when embed_summaries ran for one graph + kind."""

    kind: str
    total: int = 0
    embedded: int = 0
    skipped_existing: int = 0
    failed: int = 0


class CommunitySummarizer:
    """Registry-aware summarizer for read-only / flat community kinds.

    Construct once per request; call ``summarize_all(kind)`` to summarise
    every community of that kind. Skips communities whose ``summary`` is
    already set unless ``force_rebuild=True``.

    Caller must pre-check the kind is supported via ``supported_kinds()``.
    """

    # Kinds this summarizer knows how to handle. Entity-Leiden is not
    # listed because community_tasks.py + analytics_service own that path.
    _SUPPORTED_KINDS: tuple[str, ...] = ("chunk",)

    def __init__(
        self,
        *,
        openai_client: AsyncOpenAI | None = None,
        model: str = "gpt-4o-mini",
        concurrency: int | None = None,
    ) -> None:
        # Lazy-default the OpenAI client so tests can inject a mock without
        # needing OPENAI_API_KEY in the env at import time.
        if openai_client is None:
            openai_client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)
        self._client = openai_client
        self._model = model
        self._semaphore = asyncio.Semaphore(
            concurrency or getattr(settings, "LLM_SUMMARY_CONCURRENCY", 5)
        )

    @classmethod
    def supported_kinds(cls) -> tuple[str, ...]:
        """Kinds this class can summarise. Endpoints use this for 400
        responses on kinds we don't summarise via the new endpoint."""
        return cls._SUPPORTED_KINDS

    # ── Public API ────────────────────────────────────────────────────────────

    async def summarize_all(
        self,
        graph_id: str,
        kind: str,
        *,
        force_rebuild: bool = False,
    ) -> SummarizeReport:
        """Dispatch to the kind-specific path. Raises
        ``UnknownCommunityKindError`` for off-registry kinds, ``ValueError``
        for registered kinds this summarizer does not handle (e.g. entity,
        which has its own Celery path)."""
        spec = get_kind(kind)  # raises UnknownCommunityKindError
        if spec.kind not in self._SUPPORTED_KINDS:
            raise ValueError(
                f"CommunitySummarizer does not handle kind {spec.kind!r}. "
                f"Supported here: {self._SUPPORTED_KINDS}. Entity-Leiden "
                "summaries are generated by the detect Celery task."
            )
        if spec.kind == "chunk":
            return await self._summarize_chunk_all(graph_id, force_rebuild)
        # Unreachable — kept for typing exhaustiveness
        raise UnknownCommunityKindError(spec.kind)

    # ── Chunk-Louvain path ───────────────────────────────────────────────────

    async def _summarize_chunk_all(
        self, graph_id: str, force_rebuild: bool
    ) -> SummarizeReport:
        """Skip singletons; summarise real clusters via JSON-output LLM call."""
        report = SummarizeReport(kind="chunk")

        rows = await neo4j_client.execute_query(
            (
                "MATCH (cc:ChunkCommunity {graph_id: $graph_id}) "
                "RETURN cc.community_id AS community_id, "
                "       cc.size AS size, "
                "       cc.summary AS summary"
            ),
            {"graph_id": graph_id},
        )
        report.total = len(rows)

        tasks = []
        for r in rows:
            size = r.get("size") or 0
            if size < 2:
                report.skipped_singleton += 1
                continue
            if not force_rebuild and r.get("summary"):
                report.skipped_existing += 1
                continue
            tasks.append(self._summarize_chunk_one(graph_id, r["community_id"], size))

        results = await asyncio.gather(*tasks, return_exceptions=True)
        report.summarized = sum(1 for x in results if x is True)
        report.failed = sum(
            1 for x in results if x is False or isinstance(x, Exception)
        )
        return report

    async def summarize_one_chunk(
        self,
        graph_id: str,
        community_id: str,
        *,
        force_rebuild: bool = False,
    ) -> dict[str, Any] | None:
        """Summarise a single chunk community on demand.

        Used by the future ``describe_community`` agent tool (STORY-4d)
        when an agent asks about a community that has no stored summary.
        Returns the written summary dict, or None when skipped (singleton)
        or no existing summary needed regeneration.
        """
        row = await neo4j_client.execute_query(
            (
                "MATCH (cc:ChunkCommunity "
                "{community_id: $community_id, graph_id: $graph_id}) "
                "RETURN cc.size AS size, cc.summary AS summary"
            ),
            {"community_id": community_id, "graph_id": graph_id},
        )
        if not row:
            return None
        size = row[0].get("size") or 0
        if size < 2:
            return None
        if not force_rebuild and row[0].get("summary"):
            return None
        ok = await self._summarize_chunk_one(graph_id, community_id, size)
        if not ok:
            return None
        # Fetch what we just wrote so the caller gets it back atomically.
        out = await neo4j_client.execute_query(
            (
                "MATCH (cc:ChunkCommunity "
                "{community_id: $community_id, graph_id: $graph_id}) "
                "RETURN cc.summary AS summary, "
                "       cc.summary_keywords AS keywords, "
                "       cc.summary_excerpt AS excerpt, "
                "       cc.summary_member_count AS member_count"
            ),
            {"community_id": community_id, "graph_id": graph_id},
        )
        if not out:
            return None
        return {
            "community_id": community_id,
            "summary": out[0].get("summary"),
            "keywords": json.loads(out[0].get("keywords") or "[]"),
            "excerpt": out[0].get("excerpt"),
            "member_count": out[0].get("member_count"),
        }

    async def _summarize_chunk_one(
        self, graph_id: str, community_id: str, total_size: int
    ) -> bool:
        """Sample chunks, call LLM with JSON-output mode, write 3-field summary."""
        # Deterministic top-K sample by chunk_id ordering. Louvain produced
        # stable ids, so this gives reproducible results across re-runs and
        # doesn't depend on random seeds.
        rows = await neo4j_client.execute_query(
            (
                "MATCH (chunk:Chunk {graph_id: $graph_id})"
                "-[:IN_CHUNK_COMMUNITY]->"
                "(cc:ChunkCommunity {community_id: $community_id, "
                "graph_id: $graph_id}) "
                "RETURN chunk.text AS text, chunk.id AS id "
                "ORDER BY chunk.id "
                "LIMIT $k"
            ),
            {
                "graph_id": graph_id,
                "community_id": community_id,
                "k": _CHUNK_SAMPLE_K,
            },
        )
        chunk_texts = [r["text"] for r in rows if r.get("text")]
        if not chunk_texts:
            return False

        chunk_block = "\n\n".join(
            f"[{i + 1}] {t[:_CHUNK_TRUNC_CHARS]}" for i, t in enumerate(chunk_texts)
        )
        prompt = _CHUNK_PROMPT_TEMPLATE.format(
            sampled=len(chunk_texts), total=total_size, chunk_block=chunk_block
        )

        try:
            raw = await self._call_llm_json(prompt)
            parsed = self._safe_parse_chunk_response(raw)
        except Exception as exc:
            logger.warning("chunk summary LLM failed for %s: %s", community_id, exc)
            return False

        if not parsed["summary"]:
            return False

        await neo4j_client.execute_query(
            (
                "MATCH (cc:ChunkCommunity "
                "{community_id: $community_id, graph_id: $graph_id}) "
                "SET cc.summary = $summary, "
                "    cc.summary_keywords = $keywords, "
                "    cc.summary_excerpt = $excerpt, "
                "    cc.summary_model = $model, "
                "    cc.summary_member_count = $member_count, "
                "    cc.summary_sampled = $sampled, "
                "    cc.summary_at = datetime(), "
                "    cc.updated_at = datetime()"
            ),
            {
                "community_id": community_id,
                "graph_id": graph_id,
                "summary": parsed["summary"],
                "keywords": json.dumps(parsed["keywords"]),
                "excerpt": parsed["excerpt"],
                "model": self._model,
                "member_count": total_size,
                "sampled": len(chunk_texts),
            },
        )
        return True

    @staticmethod
    def _safe_parse_chunk_response(raw: str) -> dict[str, Any]:
        """Tolerant JSON parse — fall back to using the whole text as
        the summary if the model didn't honour JSON-output mode."""
        try:
            obj = json.loads(raw)
            if isinstance(obj, dict):
                summary = obj.get("summary") or ""
                keywords = obj.get("keywords") or []
                excerpt = obj.get("representative_excerpt") or ""
                if not isinstance(keywords, list):
                    keywords = []
                return {
                    "summary": str(summary)[:2000],
                    "keywords": [str(k)[:120] for k in keywords[:20]],
                    "excerpt": str(excerpt)[:600],
                }
        except (json.JSONDecodeError, TypeError):
            pass
        # Fallback: treat the whole text as the summary, leave structured
        # fields empty so callers can detect partial output.
        return {"summary": str(raw)[:2000], "keywords": [], "excerpt": ""}

    # ── Embedding (STORY-4c) ─────────────────────────────────────────────────

    async def embed_summaries(
        self,
        graph_id: str,
        kind: str,
        *,
        force_rebuild: bool = False,
    ) -> EmbedReport:
        """Compute summary embeddings for the given kind.

        Looks up the per-kind ``embedding_property`` from the registry —
        entity uses ``embedding`` (Celery-detector convention, pre-existing),
        chunk uses ``summary_embedding`` (under the ``summary_*`` namespace).
        Skips communities that already have an embedding unless
        ``force_rebuild`` is True.

        The vector index ``spec.index_name`` should already exist (created
        on app startup via ``ensure_community_vector_indexes``).
        """
        spec = get_kind(kind)
        emb_prop = spec.embedding_property
        community_label = spec.community_label
        id_property = spec.id_property

        # Pull communities that have a summary AND (no embedding OR force).
        # Property names come from the registry — compile-time constants,
        # safe for f-string interpolation.
        condition = f"AND c.`{emb_prop}` IS NULL"
        if force_rebuild:
            condition = ""
        rows = await neo4j_client.execute_query(
            (
                f"MATCH (c:`{community_label}` {{graph_id: $graph_id}}) "
                f"WHERE c.summary IS NOT NULL {condition} "
                f"RETURN c.`{id_property}` AS community_id, "
                "c.summary AS summary"
            ),
            {"graph_id": graph_id},
        )
        report = EmbedReport(kind=kind, total=len(rows))

        # Count communities that already have an embedding so the response
        # is informative even when there's nothing left to do. Always
        # compute this when not force_rebuild — it's the diagnostic that
        # tells the caller "you already ran this".
        if not force_rebuild:
            counts = await neo4j_client.execute_query(
                (
                    f"MATCH (c:`{community_label}` {{graph_id: $graph_id}}) "
                    f"WHERE c.summary IS NOT NULL AND "
                    f"c.`{emb_prop}` IS NOT NULL "
                    "RETURN count(c) AS cnt"
                ),
                {"graph_id": graph_id},
            )
            report.skipped_existing = counts[0]["cnt"] if counts else 0

        if not rows:
            return report

        embedder = self._get_embedder()

        async def _embed_one(community_id: str, summary_text: str) -> bool:
            async with self._semaphore:
                try:
                    # Embedder may be sync or async depending on SDK
                    raw = embedder.embed_query(summary_text)
                    embedding = await raw if hasattr(raw, "__await__") else raw
                except Exception as exc:
                    logger.warning(
                        "embedding failed for %s/%s: %s", kind, community_id, exc
                    )
                    return False
                await neo4j_client.execute_query(
                    (
                        f"MATCH (c:`{community_label}` "
                        f"{{`{id_property}`: $community_id, graph_id: $graph_id}}) "
                        f"SET c.`{emb_prop}` = $embedding, "
                        "    c.summary_embedded_at = datetime()"
                    ),
                    {
                        "community_id": community_id,
                        "graph_id": graph_id,
                        "embedding": embedding,
                    },
                )
                return True

        results = await asyncio.gather(
            *(_embed_one(r["community_id"], r["summary"]) for r in rows),
            return_exceptions=True,
        )
        report.embedded = sum(1 for x in results if x is True)
        report.failed = sum(
            1 for x in results if x is False or isinstance(x, Exception)
        )
        return report

    def _get_embedder(self):
        """Lazy-construct the embedder. neo4j_graphrag.OpenAIEmbeddings
        is the same path the chat retriever and entity-Leiden detector use,
        so we match dimensions (3072 for text-embedding-3-large) and
        provider routing."""
        if getattr(self, "_embedder", None) is None:
            from neo4j_graphrag.embeddings import OpenAIEmbeddings

            model = getattr(settings, "EMBEDDING_MODEL", "text-embedding-3-large")
            self._embedder = OpenAIEmbeddings(
                api_key=settings.OPENAI_API_KEY, model=model
            )
        return self._embedder

    # ── LLM call plumbing ─────────────────────────────────────────────────────

    async def _call_llm_json(self, prompt: str) -> str:
        """JSON-output completion. Most OpenAI-compatible providers honour
        ``response_format``; the safe-parse layer catches the rare provider
        that doesn't."""
        async with self._semaphore:
            resp = await self._client.chat.completions.create(
                model=self._model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a knowledge graph analyst. Summarise "
                            "the cluster of chunks. Return ONLY valid JSON."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,
                max_tokens=800,
                response_format={"type": "json_object"},
            )
            return (resp.choices[0].message.content or "").strip()


# ── Vector index ensure (called on app startup) ─────────────────────────────


async def ensure_community_vector_indexes() -> None:
    """Create the vector index for every registered community kind.

    Idempotent (``CREATE VECTOR INDEX … IF NOT EXISTS``). Called from
    ``main.py`` lifespan so the index exists by the time the first
    summarize / embed / find_communities call lands.

    Dimensions match ``text-embedding-3-large`` (3072) — the embedding
    model used by every other path in the codebase. If a deployment uses
    a different embedding model, this is the place to thread that in
    (the registry could carry ``embedding_dim`` too, but a single
    deployment-wide model is the only configuration we support today).
    """
    dim = getattr(settings, "EMBEDDING_DIMENSIONS", 3072)
    for spec in COMMUNITY_KINDS.values():
        query = (
            f"CREATE VECTOR INDEX {spec.index_name} IF NOT EXISTS "
            f"FOR (c:`{spec.community_label}`) "
            f"ON (c.`{spec.embedding_property}`) "
            "OPTIONS {indexConfig: { "
            f"`vector.dimensions`: {dim}, "
            "`vector.similarity_function`: 'cosine' "
            "}}"
        )
        try:
            await neo4j_client.execute_write_query(query)
            logger.info(
                "Ensured community vector index %s on :%s(%s)",
                spec.index_name,
                spec.community_label,
                spec.embedding_property,
            )
        except Exception as exc:
            # Index creation failures during startup shouldn't crash the
            # whole service — log + continue. Subsequent runs retry.
            logger.warning("Could not create %s vector index: %s", spec.index_name, exc)
