FROM public.ecr.aws/lambda/python:3.11


# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code. This copies EVERYTHING inside the app folder to the lambda root.
COPY ./app ${LAMBDA_TASK_ROOT}

ENV PYTHONPATH="/:/app"

WORKDIR /app
# Logging for debugging
RUN echo "Contents of ${LAMBDA_TASK_ROOT} directory:" && ls -la ${LAMBDA_TASK_ROOT}

CMD ["main.handler"]