FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11


COPY requirements.txt /app/

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code.
COPY ./app /app

WORKDIR /app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]